CREATE DATABASE IF NOT EXISTS pigeon_pedigree CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pigeon_pedigree;

CREATE TABLE IF NOT EXISTS pigeons (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL,
  color VARCHAR(100) DEFAULT NULL,
  owner VARCHAR(150) DEFAULT NULL,
  image_url LONGTEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pedigree_data (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  pigeon_id BIGINT UNSIGNED NOT NULL,
  type VARCHAR(30) NOT NULL,
  details JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_pedigree_pigeon_id (pigeon_id),
  CONSTRAINT fk_pedigree_pigeon FOREIGN KEY (pigeon_id) REFERENCES pigeons(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
